# Generated by Django 4.2.4 on 2023-08-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='user',
        ),
    ]
