# Generated by Django 4.2.4 on 2023-08-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_answers_user_questions_user_tags_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(to='forum.tags', verbose_name='タグ名'),
        ),
    ]
